<a href="https://colab.research.google.com/github/VAISH-16/INVENTORY-MANAGEMENT-SYSTEM/blob/main/Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json

In [ ]:
record = { 556671: {'Product name' : 'Dairy Milk', 'Brand Name' : 'Cadbury', 'Opening Quantity' : 100 , 'Closing Quantity' : 100, 'Sale Price' : 100, 'Purchase Price': 80 },
           556672: {'Product name' : 'Kitkat','Brand Name' : 'Nestle global', 'Opening Quantity': 100 , 'Closing Quantity':100   ,'Sale Price': 40, 'Purchase Price': 20},
            556673: {'Product name' : 'Five star', 'Brand Name' :'Cadbury', 'Opening Quantity':100 , 'Closing Quantity':100    ,'Sale Price': 10, 'Purchase Price': 5},
            556674: {'Product name' :'Eclairs', 'Brand Name' : 'Cadbury', 'Opening Quantity':100, 'Closing Quantity':100    ,'Sale Price': 2, 'Purchase Price': 1},
            556675: {'Product name' : 'Dark Fantasy', 'Brand Name' : 'SunFeast', 'Opening Quantity':100 , 'Closing Quantity':100   ,'Sale Price': 50, 'Purchase Price':40},
            556676: {'Product name' : 'Perk', 'Brand Name' :'Cadbury', 'Opening Quantity':100 , 'Closing Quantity':100   ,'Sale Price': 20, 'Purchase Price':15},
            556677: {'Product name' :'Bournville', 'Brand Name': 'Cadbury', 'Opening Quantity':100,  'Closing Quantity':100   ,'Sale Price': 100 , 'Purchase Price':75},
            556678: {'Product name' :'Dark Chocolate','Brand Name' :'Amul', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556679:{'Product name' :'Munch','Brand Name' :'Nestle', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price': 8} ,
            556680:{'Product name' :'Milkybar','Brand Name' :'Nestle', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price':8},
            556681:{'Product name' :'Melody','Brand Name' :'Parle', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 50, 'Purchase Price':40},
            556682:{'Product name' :'Bounty','Brand Name' :'Procter & Gamble', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556683:{'Product name' :'Ferrero Rocher','Brand Name' :'Ferrero Rocher', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556684:{'Product name' :'Toblerone','Brand Name' :'Cadbury', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556685:{'Product name' :'Mars','Brand Name' :'Mars', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 50, 'Purchase Price':40},
            556686:{'Product name' :'Gems','Brand Name' :'Cadbury', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price':8},
            556687:{'Product name' :'Temptation','Brand Name' :'Cadbury', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556688:{'Product name' :'Safari','Brand Name' :'Gandour', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 80, 'Purchase Price':70},
            556689:{'Product name' :'Galaxy','Brand Name' :'Mars', 'Opening Quantity':100   , 'Closing Quantity': 100   ,'Sale Price': 100, 'Purchase Price':80},
            556690:{'Product name' :'Crispello','Brand Name' :'Cadbury', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 20, 'Purchase Price':15},
            556691:{'Product name' :'BarOne','Brand Name' :'Nestle', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 30, 'Purchase Price':20},
            556692:{'Product name' :'Nutties','Brand Name' :'Nutties', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 40, 'Purchase Price':35},
            556693:{'Product name' :'Alpenliebe','Brand Name' :'Perfetti Van Melle', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 2, 'Purchase Price':1},
            556694:{'Product name' :'Creamfills','Brand Name' :'Perfetti Van Melle', 'Opening Quantity':100, 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price':8},
            556695:{'Product name' :'Candyman','Brand Name' :'ITC Foods', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price':8},
            556696:{'Product name' :'Pulse','Brand Name' :'DS Group', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 2, 'Purchase Price':1},
            556697:{'Product name' :'Nestle','Brand Name' :'Nestle', 'Opening Quantity':100  , 'Closing Quantity': 100   ,'Sale Price': 10, 'Purchase Price':8},
            556698:{'Product name' :'Kismi','Brand Name' :'Parle', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 2, 'Purchase Price':1},
            556699:{'Product name' :'Mango Bite','Brand Name' :'Parle', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 2, 'Purchase Price':1},
            556700:{'Product name' :'Coffy Bite','Brand Name' :'Lotte', 'Opening Quantity':100 , 'Closing Quantity': 100   ,'Sale Price': 2, 'Purchase Price':1}

            }

In [ ]:
record

{556671: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Dairy Milk',
  'Purchase Price': 80,
  'Sale Price': 100},
 556672: {'Brand Name': 'Nestle global',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Kitkat',
  'Purchase Price': 20,
  'Sale Price': 40},
 556673: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Five star',
  'Purchase Price': 5,
  'Sale Price': 10},
 556674: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Eclairs',
  'Purchase Price': 1,
  'Sale Price': 2},
 556675: {'Brand Name': 'SunFeast',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Dark Fantasy',
  'Purchase Price': 40,
  'Sale Price': 50},
 556676: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Perk',
  'Purchase Price': 15,
  'Sale Price': 20},
 556677: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Bournville',
  'Purchase Price': 75,
  'Sale Price': 100},
 556678: {'Brand Name': 'Amul',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Dark Chocolate',
  'Purchase Price': 80,
  'Sale Price': 100},
 556679: {'Brand Name': 'Nestle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Munch',
  'Purchase Price': 8,
  'Sale Price': 10},
 556680: {'Brand Name': 'Nestle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Milkybar',
  'Purchase Price': 8,
  'Sale Price': 10},
 556681: {'Brand Name': 'Parle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Melody',
  'Purchase Price': 40,
  'Sale Price': 50},
 556682: {'Brand Name': 'Procter & Gamble',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Bounty',
  'Purchase Price': 80,
  'Sale Price': 100},
 556683: {'Brand Name': 'Ferrero Rocher',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Ferrero Rocher',
  'Purchase Price': 80,
  'Sale Price': 100},
 556684: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Toblerone',
  'Purchase Price': 80,
  'Sale Price': 100},
 556685: {'Brand Name': 'Mars',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Mars',
  'Purchase Price': 40,
  'Sale Price': 50},
 556686: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Gems',
  'Purchase Price': 8,
  'Sale Price': 10},
 556687: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Temptation',
  'Purchase Price': 80,
  'Sale Price': 100},
 556688: {'Brand Name': 'Gandour',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Safari',
  'Purchase Price': 70,
  'Sale Price': 80},
 556689: {'Brand Name': 'Mars',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Galaxy',
  'Purchase Price': 80,
  'Sale Price': 100},
 556690: {'Brand Name': 'Cadbury',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Crispello',
  'Purchase Price': 15,
  'Sale Price': 20},
 556691: {'Brand Name': 'Nestle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'BarOne',
  'Purchase Price': 20,
  'Sale Price': 30},
 556692: {'Brand Name': 'Nutties',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Nutties',
  'Purchase Price': 35,
  'Sale Price': 40},
 556693: {'Brand Name': 'Perfetti Van Melle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Alpenliebe',
  'Purchase Price': 1,
  'Sale Price': 2},
 556694: {'Brand Name': 'Perfetti Van Melle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Creamfills',
  'Purchase Price': 8,
  'Sale Price': 10},
 556695: {'Brand Name': 'ITC Foods',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Candyman',
  'Purchase Price': 8,
  'Sale Price': 10},
 556696: {'Brand Name': 'DS Group',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Pulse',
  'Purchase Price': 1,
  'Sale Price': 2},
 556697: {'Brand Name': 'Nestle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Nestle',
  'Purchase Price': 8,
  'Sale Price': 10},
 556698: {'Brand Name': 'Parle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Kismi',
  'Purchase Price': 1,
  'Sale Price': 2},
 556699: {'Brand Name': 'Parle',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Mango Bite',
  'Purchase Price': 1,
  'Sale Price': 2},
 556700: {'Brand Name': 'Lotte',
  'Closing Quantity': 100,
  'Opening Quantity': 100,
  'Product name': 'Coffy Bite',
  'Purchase Price': 1,
  'Sale Price': 2}}

In [ ]:
js = json.dumps(record)

In [ ]:
js

'{"556671": {"Product name": "Dairy Milk", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556672": {"Product name": "Kitkat", "Brand Name": "Nestle global", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 40, "Purchase Price": 20}, "556673": {"Product name": "Five star", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 5}, "556674": {"Product name": "Eclairs", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}, "556675": {"Product name": "Dark Fantasy", "Brand Name": "SunFeast", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 50, "Purchase Price": 40}, "556676": {"Product name": "Perk", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 20, "Purchase Price": 15}, "556677": {"Product name": "Bournville", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 75}, "556678": {"Product name": "Dark Chocolate", "Brand Name": "Amul", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556679": {"Product name": "Munch", "Brand Name": "Nestle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556680": {"Product name": "Milkybar", "Brand Name": "Nestle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556681": {"Product name": "Melody", "Brand Name": "Parle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 50, "Purchase Price": 40}, "556682": {"Product name": "Bounty", "Brand Name": "Procter & Gamble", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556683": {"Product name": "Ferrero Rocher", "Brand Name": "Ferrero Rocher", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556684": {"Product name": "Toblerone", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556685": {"Product name": "Mars", "Brand Name": "Mars", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 50, "Purchase Price": 40}, "556686": {"Product name": "Gems", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556687": {"Product name": "Temptation", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556688": {"Product name": "Safari", "Brand Name": "Gandour", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 80, "Purchase Price": 70}, "556689": {"Product name": "Galaxy", "Brand Name": "Mars", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 100, "Purchase Price": 80}, "556690": {"Product name": "Crispello", "Brand Name": "Cadbury", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 20, "Purchase Price": 15}, "556691": {"Product name": "BarOne", "Brand Name": "Nestle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 30, "Purchase Price": 20}, "556692": {"Product name": "Nutties", "Brand Name": "Nutties", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 40, "Purchase Price": 35}, "556693": {"Product name": "Alpenliebe", "Brand Name": "Perfetti Van Melle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}, "556694": {"Product name": "Creamfills", "Brand Name": "Perfetti Van Melle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556695": {"Product name": "Candyman", "Brand Name": "ITC Foods", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556696": {"Product name": "Pulse", "Brand Name": "DS Group", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}, "556697": {"Product name": "Nestle", "Brand Name": "Nestle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 10, "Purchase Price": 8}, "556698": {"Product name": "Kismi", "Brand Name": "Parle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}, "556699": {"Product name": "Mango Bite", "Brand Name": "Parle", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}, "556700": {"Product name": "Coffy Bite", "Brand Name": "Lotte", "Opening Quantity": 100, "Closing Quantity": 100, "Sale Price": 2, "Purchase Price": 1}}'

In [ ]:

Dairy_Milk = 24 #@param {type:"slider", min:0, max:100, step:1}
Kitkat = 7 #@param {type:"slider", min:0, max:100, step:1}
Five_star = 37 #@param {type:"slider", min:0, max:100, step:1}
Eclairs = 34 #@param {type:"slider", min:0, max:100, step:1}
Dark_Fantacy = 46 #@param {type:"slider", min:0, max:100, step:1}
Perk = 39 #@param {type:"slider", min:0, max:100, step:1}
Bournville = 29 #@param {type:"slider", min:0, max:100, step:1}
Dark_Chocolate = 21 #@param {type:"slider", min:0, max:100, step:1}
Munch = 0 #@param {type:"slider", min:0, max:100, step:1}
Milkybar = 0 #@param {type:"slider", min:0, max:100, step:1}
Melody = 0 #@param {type:"slider", min:0, max:100, step:1}
Bounty = 47 #@param {type:"slider", min:0, max:100, step:1}
Ferrero_Rocher = 0 #@param {type:"slider", min:0, max:100, step:1}
Toblerone = 31 #@param {type:"slider", min:0, max:100, step:1}
Mars = 80 #@param {type:"slider", min:0, max:100, step:1}
Gems = 0 #@param {type:"slider", min:0, max:100, step:1}
Temptation = 24 #@param {type:"slider", min:0, max:100, step:1}
Safari = 0 #@param {type:"slider", min:0, max:100, step:1}
Galaxy = 0 #@param {type:"slider", min:0, max:100, step:1}
Crispello = 0 #@param {type:"slider", min:0, max:100, step:1}
BarOne = 0 #@param {type:"slider", min:0, max:100, step:1}
Nutties = 0 #@param {type:"slider", min:0, max:100, step:1}
Alpenliebe = 0 #@param {type:"slider", min:0, max:100, step:1}
Creamfills = 0 #@param {type:"slider", min:0, max:100, step:1}
Candyman = 0 #@param {type:"slider", min:0, max:100, step:1}
Pulse = 0 #@param {type:"slider", min:0, max:100, step:1}
Nestle = 0 #@param {type:"slider", min:0, max:100, step:1}
Kismi = 0 #@param {type:"slider", min:0, max:100, step:1}
Mango_Bite = 0 #@param {type:"slider", min:0, max:100, step:1}
Coffy_Bite = 0 #@param {type:"slider", min:0, max:100, step:1}

In [ ]:
Total_Sale = Dairy_Milk + Kitkat + Five_star + Eclairs + Dark_Fantacy + Perk + Bournville + Dark_Chocolate + Munch + Milkybar + Melody +Bounty + Ferrero_Rocher + Toblerone + Mars + Gems + Temptation + Safari + Galaxy + Crispello + BarOne + Nutties + Alpenliebe + Creamfills + Candyman + Pulse + Nestle + Kismi + Mango_Bite + Coffy_Bite
print('Total Sale is',Total_Sale, 'Chocolates')

Total Sale is 419 Chocolates

In [ ]:

Product_ID = input('Enter the Product ID : ')

if(Product_ID == '556671'):
   print('Customers have purchased',  Dairy_Milk,'Dairy Milk')
   record[556671]['Closing Quantity'] = record[556671]['Opening Quantity'] - Dairy_Milk
   Closing_Quantity = record[556671]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556671]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556672'):
   print('Customers have purchased' , Kitkat,'Kitkat')
   record[556672]['Closing Quantity'] = record[556672]['Opening Quantity'] - Kitkat
   Closing_Quantity = record[556672]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556672]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556673'):
   
   print('Customers have purchased' , Five_star,'Five Star')
   record[556673]['Closing Quantity'] = record[556673]['Opening Quantity'] - Five_star
   Closing_Quantity = record[556673]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556673]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556674'):
   print('Customers have purchased' , Eclairs,'Eclairs')
   record[556674]['Closing Quantity'] = record[556674]['Opening Quantity'] - Eclairs
   Closing_Quantity = record[556674]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556674]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556675'):
   print('Customers have purchased' , Dark_Fantasy, 'Dark Fantasy')
   record[556675]['Closing Quantity'] = record[556675]['Opening Quantity'] - Dark_Fantasy
   Closing_Quantity = record[556675]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556675]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556676'):
   print('Customers have purchased' , Perk,'Perk')
   record[556676]['Closing Quantity'] = record[556676]['Opening Quantity'] - Perk
   Closing_Quantity = record[556676]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556676]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556677'):
   print('Customers have purchased' , Bournville,'Bournville')
   record[556677]['Closing Quantity'] = record[556677]['Opening Quantity'] - Bournville
   Closing_Quantity = record[556677]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556677]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)
   
elif(Product_ID == '556678'):
   print('Customers have purchased' , Dark_Chocolate, 'Dark Chocolate')
   record[556678]['Closing Quantity'] = record[556678]['Opening Quantity'] - Dark_Chocolate
   Closing_Quantity = record[556678]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556678]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556679'):
   print('Customers have purchased',  Munch,'Munch')
   record[556679]['Closing Quantity'] = record[556679]['Opening Quantity'] - Munch
   Closing_Quantity = record[556679]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556679]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556680'):
   print('Customers have purchased',  Milkybar,'Milkybar')
   record[556680]['Closing Quantity'] = record[556680]['Opening Quantity'] - Milkybar
   Closing_Quantity = record[556680]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556680]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

if(Product_ID == '556681'):
   print('Customers have purchased',  Melody,'Melody')
   record[556681]['Closing Quantity'] = record[556681]['Opening Quantity'] - Melody
   Closing_Quantity = record[556681]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556681]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556682'):
   print('Customers have purchased',  Bounty ,'Bounty')
   record[556682]['Closing Quantity'] = record[556682]['Opening Quantity'] - Bounty
   Closing_Quantity = record[556682]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556682]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556683'):
   print('Customers have purchased',  Ferrero_Rocher,'Ferrero Rocher')
   record[556683]['Closing Quantity'] = record[556683]['Opening Quantity'] - Ferrero_Rocher
   Closing_Quantity = record[556683]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556683]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556684'):
   print('Customers have purchased',  Toblerone,'Toblerone')
   record[556684]['Closing Quantity'] = record[556684]['Opening Quantity'] - Toblerone
   Closing_Quantity = record[556684]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556684]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556685'):
   print('Customers have purchased',  Mars,'Mars')
   record[556685]['Closing Quantity'] = record[556685]['Opening Quantity'] - Mars
   Closing_Quantity = record[556685]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556685]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556686'):
   print('Customers have purchased',  Gems,'Gems')
   record[556686]['Closing Quantity'] = record[556686]['Opening Quantity'] - Gems
   Closing_Quantity = record[556686]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556686]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556687'):
   print('Customers have purchased',  Temptation,'Temptation')
   record[556687]['Closing Quantity'] = record[556687]['Opening Quantity'] - Temptation
   Closing_Quantity = record[556687]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556687]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556688'):
   print('Customers have purchased',  Safari,'Safari')
   record[556688]['Closing Quantity'] = record[556688]['Opening Quantity'] - Safari
   Closing_Quantity = record[556688]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556688]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556689'):
   print('Customers have purchased',  Galaxy,'Galaxy')
   record[556689]['Closing Quantity'] = record[556689]['Opening Quantity'] - Galaxy
   Closing_Quantity = record[556689]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556689]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556690'):
   print('Customers have purchased',  Crispello,'Crispello')
   record[556690]['Closing Quantity'] = record[556690]['Opening Quantity'] - Crispello
   Closing_Quantity = record[556690]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556690]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556691'):
   print('Customers have purchased',  BarOne,'BarOne')
   record[556691]['Closing Quantity'] = record[556691]['Opening Quantity'] - BarOne
   Closing_Quantity = record[556691]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556691]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

if(Product_ID == '556692'):
   print('Customers have purchased',  Nutties,'Nutties')
   record[556692]['Closing Quantity'] = record[556692]['Opening Quantity'] - Nutties
   Closing_Quantity = record[556692]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556692]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556693'):
   print('Customers have purchased',  Alpenliebe,'Alpenliebe')
   record[556693]['Closing Quantity'] = record[556693]['Opening Quantity'] - Alpenliebe
   Closing_Quantity = record[556693]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556693]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556694'):
   print('Customers have purchased',  Creamfills,'Creamfills')
   record[556694]['Closing Quantity'] = record[556694]['Opening Quantity'] - Creamfills
   Closing_Quantity = record[556694]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556694]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556695'):
   print('Customers have purchased',  Candyman,'Candyman')
   record[556695]['Closing Quantity'] = record[556695]['Opening Quantity'] - Candyman
   Closing_Quantity = record[556695]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556695]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556696'):
   print('Customers have purchased',  Pulse,'Pulse')
   record[556696]['Closing Quantity'] = record[556696]['Opening Quantity'] - Pulse
   Closing_Quantity = record[556696]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556696]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556697'):
   print('Customers have purchased',  Nestle,'Nestle')
   record[556680]['Closing Quantity'] = record[556680]['Opening Quantity'] - Nestle
   Closing_Quantity = record[556680]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556680]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556698'):
   print('Customers have purchased',  Kismi,'Kismi')
   record[556698]['Closing Quantity'] = record[556698]['Opening Quantity'] - Kismi
   Closing_Quantity = record[556698]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556698]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556699'):
   print('Customers have purchased',  Mango_Bite,'Mango_Bite')
   record[556699]['Closing Quantity'] = record[556699]['Opening Quantity'] - Mango_Bite
   Closing_Quantity = record[556699]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556699]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

elif(Product_ID == '556700'):
   print('Customers have purchased',  Coffy_Bite,'Coffy_Bite')
   record[556700]['Closing Quantity'] = record[556700]['Opening Quantity'] - Coffy_Bite
   Closing_Quantity = record[556700]['Closing Quantity']
   print('Closing Quantity is ',Closing_Quantity  )
   Opening_Quantity = record[556700]['Opening Quantity']
   print('Opening Quantity was ', Opening_Quantity)

else:
    print("********Invalid Product ID********* ")

Enter the Product ID : 556700
Customers have purchased 0 Coffy_Bite
Closing Quantity is  100
Opening Quantity was  100

In [ ]:
profit1 = 0
profit2 = 0
profit3 = 0
profit4 = 0
profit5 = 0
profit6 = 0
profit7 = 0
profit8 = 0
profit9 = 0
profit10 = 0
profit11 = 0
profit12 = 0
profit13 = 0
profit14 = 0
profit15 = 0
profit16 = 0
profit17 = 0
profit18 = 0
profit19 = 0
profit10 = 0
profit21 = 0
profit22 = 0
profit23 = 0
profit24 = 0
profit25 = 0
profit26 = 0
profit27 = 0
profit28 = 0
profit29 = 0
profit30 = 0
print("To check your profit ")

if(Dairy_Milk != 0):
   Sale_at = Dairy_Milk * record[556671]['Sale Price']
   Purchase_at = Dairy_Milk * record[556671]['Purchase Price']
   profit1 =  Sale_at - Purchase_at 
   print("Hurray you have got profit of Rs",profit1,"on Dairy Milk")
   
if(Kitkat != 0):
   Sale_at = Kitkat  * record[556672]['Sale Price']
   Purchase_at = Kitkat * record[556672]['Purchase Price']
   profit2 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit2,"on Kitkat")
   
if(Five_star != 0):
   Sale_at = Five_star * record[556673]['Sale Price']
   Purchase_at = Five_star * record[556673]['Purchase Price']
   profit3 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit3,"on Five Star")
   
if(Eclairs != 0):
   Sale_at = Eclairs * record[556674]['Sale Price']
   Purchase_at = Eclairs * record[556674]['Purchase Price']
   profit4 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit4,"on Eclairs")
   
if(Dark_Fantacy != 0):
   Sale_at = Dark_Fantacy * record[556675]['Sale Price']
   Purchase_at = Dark_Fantacy * record[556675]['Purchase Price']
   profit5 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit5,"on Dark Fantacy")
   
elif(Perk != 0):
   Product_name = record[556676]['Product name']
   Sale_at = Perk * record[556676]['Sale Price']
   Purchase_at = Perk * record[556676]['Purchase Price']
   profit6 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit6,"on Perk")
   
if(Bournville != 0):
   Sale_at = Bournville * record[556677]['Sale Price']
   Purchase_at = Bournville * record[556677]['Purchase Price']
   profit7 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit7,"on Bournville")
   
if(Dark_Chocolate != 0):
   Sale_at = Dark_Chocolate * record[556678]['Sale Price']
   Purchase_at = Dark_Chocolate * record[556678]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit8,"on Dark Chocolate")
   
if(Munch != 0):
   Sale_at = Munch * record[556679]['Sale Price']
   Purchase_at = Munch * record[556679]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit9,"on Munch")
   
if(Milkybar != 0):
   Sale_at = Milkybar * record[556680]['Sale Price']
   Purchase_at = Milkybar * record[556680]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit10,"on Milkybar")

if(Melody != 0):
   Sale_at = Melody * record[556681]['Sale Price']
   Purchase_at = Melody * record[556681]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit11,"on Melody")

if(Bounty != 0):
   Sale_at = Bounty * record[556682]['Sale Price']
   Purchase_at = Bounty * record[556682]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit12,"on Bounty")

if(Ferrero_Rocher != 0):
   Sale_at = Ferrero_Rocher * record[556683]['Sale Price']
   Purchase_at = Ferrero_Rocher * record[556683]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit13,"on Ferrero Rocher")

if(Toblerone != 0):
   Sale_at = Toblerone* record[556684]['Sale Price']
   Purchase_at = Toblerone * record[556684]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit14,"on Toblerone")

if(Mars != 0):
   Sale_at = Mars * record[556685]['Sale Price']
   Purchase_at = Mars * record[556685]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit15,"on Mars")

if(Gems != 0):
   Sale_at = Gems * record[556686]['Sale Price']
   Purchase_at = Gems * record[556686]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit16,"on Gems")

if(Temptation != 0):
   Sale_at = Temptation * record[556687]['Sale Price']
   Purchase_at = Temptation * record[556687]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit17,"on Temptation")

if(Safari != 0):
   Sale_at = Safari * record[556688]['Sale Price']
   Purchase_at = Safari * record[556688]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit18,"on Safari")

if(Galaxy != 0):
   Sale_at = Galaxy * record[556689]['Sale Price']
   Purchase_at = Galaxy * record[556689]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit19,"on Galaxy")

if(Crispello != 0):
   Sale_at = Crispello * record[556690]['Sale Price']
   Purchase_at = Crispello * record[556690]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit20,"on Crispello")

if(BarOne != 0):
   Sale_at = BarOne * record[556691]['Sale Price']
   Purchase_at = BarOne * record[556691]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit21,"on BarOne")

if(Nutties != 0):
   Sale_at = Nutties * record[556692]['Sale Price']
   Purchase_at = Nutties * record[556692]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit22,"on Nutties")

if(Alpenliebe != 0):
   Sale_at = Alpenliebe * record[556693]['Sale Price']
   Purchase_at = Alpenliebe * record[556693]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit23,"on Alpenliebe")

if(Creamfills != 0):
   Sale_at = Creamfills * record[556694]['Sale Price']
   Purchase_at = Creamfills * record[556694]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit24,"on Creamfills")

if(Candyman != 0):
   Sale_at = Candyman * record[556695]['Sale Price']
   Purchase_at = Candyman * record[556695]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit25,"on Candyman")

if(Pulse != 0):
   Sale_at = Pulse * record[556696]['Sale Price']
   Purchase_at = Pulse * record[556696]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit26,"on Pulse")

if(Nestle != 0):
   Sale_at = Nestle * record[556697]['Sale Price']
   Purchase_at = Nestle * record[556697]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit27,"on Nestle")

if(Kismi != 0):
   Sale_at = Kismi * record[556698]['Sale Price']
   Purchase_at = Kismi * record[556698]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit28,"on Kismi")

if(Mango_Bite != 0):
   Sale_at = Mango_Bite * record[556699]['Sale Price']
   Purchase_at = Mango_Bite * record[556699]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit29,"on Mango Bite")

if(Coffy_Bite != 0):
   Sale_at = Coffy_Bite * record[556700]['Sale Price']
   Purchase_at = Coffy_Bite * record[556700]['Purchase Price']
   profit8 =  Sale_at - Purchase_at
   print("Hurray you have got profit of Rs",profit30,"on Coffy Bite")

Total_Profit = profit1 + profit2 + profit3 + profit4 + profit5 + profit6 + profit7 + profit8
print("Hurray Total Profit is Rs. ",Total_Profit)

To check your profit
Hurray you have got profit of Rs 480 on Dairy Milk
Hurray you have got profit of Rs 140 on Kitkat
Hurray you have got profit of Rs 185 on Five Star
Hurray you have got profit of Rs 34 on Eclairs
Hurray you have got profit of Rs 460 on Dark Fantacy
Hurray you have got profit of Rs 725 on Bournville
Hurray you have got profit of Rs 420 on Dark Chocolate
Hurray you have got profit of Rs 0 on Bounty
Hurray you have got profit of Rs 0 on Toblerone
Hurray you have got profit of Rs 0 on Mars
Hurray you have got profit of Rs 0 on Temptation
Hurray Total Profit is Rs.  2504

In [ ]:
fd = open("record.json" , 'w')
fd.write(js)
fd.close()

In [ ]:
fd = open("record.json" , 'r')
txt = fd.read()
fd.close()